### PR TITLE
Browser support config

### LINKED ISSUE #3579: Show message when trying to load Redash from an unsupported browser
Unsupported browsers: IE or old versions of Edge.

Need to update `index.html` to show a message instead of loading broken code.

### PR DESCRIPTION
**Pull request by ranbena**
## What type of PR is this?
- [x] Feature

Fixes #3579

## Description
Using [browserslist](https://github.com/browserslist/browserslist) to define which browser versions Redash supports.
List established from minimum "Async function" browser feature support ([caniuse](https://caniuse.com/#feat=async-functions)).
```json
// package.json
"browserslist": [
  "Edge >= 15",
  "Firefox >= 52",
  "Chrome >= 55",
  "Safari >= 10.1",
  "iOS >= 10.3",
  "Opera >= 42",
  "op_mob >= 46",
  "android >= 67",
  "and_chr >= 71",
  "and_ff >= 64",
  "and_uc >= 11.8",
  "samsung >= 6.2"
]
```

This list allows us to utilize some powerful tools (all adhering to list automatically):
- [x] **Babel transpiler** 🚯
  * js reduced by 2k (comparing app.js on netlify preview)
  * css no change (autoprefix still must use `-ms` for Edge browser)
  * although babel should drop "async func" and "arrow func" polyfills [according to this list](https://github.com/kangax/compat-table/blob/7572692166b1e75717c725aed8c8d83ca31493e0/data-es2016plus.js#L473-L488) - it doesn't. So I excluded these explicitly in `.babelrc`.
- [x] **Eslint rule** - error on unsupported browser feature usage 👮
  * Also available with stylelint but doesn't support less file so whatever man.
- [x] **Outdated browser detection** ~~with browserslist-useragent~~ only IE for now🚦
  * redirecting to a dedicated "browser not supported" static page (TBD).

### CODE REVIEW

File: client/app/components/app-view/index.js [hunk 1]
```diff
@@ -1,8 +1,14 @@
 import debug from 'debug';
+import { matchesUA, resolveUserAgent } from 'browserslist-useragent';
 import PromiseRejectionError from '@/lib/promise-rejection-error';
 import { ErrorHandler } from './error-handler';
 import template from './template.html';
 
+if (!matchesUA(navigator.userAgent, { allowHigherVersions: true })) {
+  // TODO: create "browser outdated" page and redirect to it
+  console.log('Your browser is outdated', resolveUserAgent(navigator.userAgent));
```
Comment (ranbena) [inline client/app/components/app-view/index.js]: Is this the place (and method) to put the redirect?

Comment (kravets-levko) [reply client/app/components/app-view/index.js]: Yes, it's the right place. And probably you don't need a page redirect: create a component with message or whatever, and conditionally show it instead of `<div ng-view>`

Comment (ranbena) [reply client/app/components/app-view/index.js]: But then we're still running potentially unsupported js for that page.
If we early redirect to a static html page, we don't have to worry about it.

Comment (kravets-levko) [reply client/app/components/app-view/index.js]: If you detect UA on client-side - you always have a chance to run unsupported code. If you'll change `app-view/template.html` to something like this - no change it will render header/footer/page:
```html
<div ng-if="$ctrl.isBrowserSupported">
  <!-- original template here -->
</div>
<div ng-if="!$ctrl.isBrowserSupported">
  Error! Error!!!! Unsupported browser!!!!111
</div>
```

Comment (kravets-levko) [reply client/app/components/app-view/index.js]: It's important that `app-view` component itself shouldn't use any unsupported features, as well as all code it uses via imports.

Comment (ranbena) [reply client/app/components/app-view/index.js]: Sounds easy and simple.
I'll do that and also add a cypress test to make sure it doesn't break.

Comment (ranbena) [reply client/app/components/app-view/index.js]: @kravets-levko does this make sense? (I'd rather it have it's own template)
```js
export default function init(ngModule) {
  ngModule.factory(
    '$exceptionHandler',
    () => function exceptionHandler(exception) {
      handler.process(exception);
    },
  );

  const isBrowserSupported = someCheck(...);
  ngModule.component('appView', {
    template: isBrowserSupported ? template : notSupportedTemplate,
    controller: isBrowserSupported ? AppViewComponent : NotSupportedCtrl,
  });
}
```

Comment (kravets-levko) [reply client/app/components/app-view/index.js]: @ranbena Yes, it's probably even better :+1:

**Comment by arikfr** [comment]
I think the initial approach of redirect is the correct one. We should assume that an unsupported feature can break the whole bundle and cause the app not to load in which case we won’t show any message to the user.

To avoid possible issues we should do the detection in a separate file we will include in index.html. Actually we can avoid redirect and just render a message. But point is: it should not depend on the bigger code base or on any of it working.

-- 
Arik Fraimovich

**Comment by ranbena** [comment]
> I think the initial approach of redirect is the correct one.

Best practice would be to determine and redirect in `static.py`.
```py
@routes.route(org_scoped_rule('/<path:path>'))
@routes.route(org_scoped_rule('/'))
@supported_browser_required  <--
@login_required
def index(**kwargs):
    return render_index()
```
but that would require re-implementing `browserlist-useragent` in Python (currently available only in js and ruby).

But going with JS has a clear problem - it's not a standalone file, but a js module.

Options:
1. Back down and import it into `app-view.js`.
2. Implement it in python (and perhaps contribute to the open source project)
3. Reimplement as standalone js file to be loaded in `index.html`.

None are perfect, my personal pref is #2 (although not my comfort zone).
Wdyt @arikfr?

**Comment by arikfr** [comment]
>  Eslint rule - error on unsupported browser feature usage 👮

If we only use browser supported features, what does Babel transpile?

**Comment by ranbena** [comment]
> If we only use browser supported features, what does Babel transpile?

It's a good question though and I'd like to know as well. My understanding is that it does not polyfill all features and if a feature is polyfilled (either with dedicated babel plugin / npm package / own util) we need to be explicitly define it to be excluded from the linter.

**Comment by ranbena** [comment]
#### What I want to do
Generate `browserslist-useragent.js` file that suits old browsers to be loaded in `client/app/index.html`.

#### The plan
Define an npm script `unsupported:build` which transpiles the `browserslist-useragent` npm package with a dedicated babel config into a single file.

@arikfr
1. Does this make sense?
2. Can babel cli transpile a node module with its dependencies? Or can webpack be used to so that?
3. How do you provide babel with a preset override? (e.g. `targets: [ "ie": 8 ]`)

**Comment by arikfr** [comment]
This is what webpack is for. Not sure about the overrides but we can have a dedicated configuration for it (maybe in a separate project?).

But I feel like we’re reinventing the wheel here. Is there some prior art on how this is done?

-- 
Arik Fraimovich

**Comment by ranbena** [comment]
Tested the redirect method in IE10 and 11 but the rest later this week (with windows machine).

File: client/app/index.html [hunk 2]
```diff
@@ -5,6 +5,18 @@
...
+        window.location.href = '/unsupported';
+      }
+      if (
+        navigator.userAgent.match('/MSIE') || // IE10
+        navigator.appVersion.match('Trident/') // IE11
+      ){
+        onIE();
+      }
+    </script>
+    <!--[if IE]><script>onIE()</script><![endif]-->
```
Comment (ranbena) [inline client/app/index.html]: IE only for now, consider using https://github.com/browserslist/browserslist-useragent in the future.

**Comment by ranbena** [comment]
@arikfr made html page static, no template. Lmk if this is what you meant.

**Comment by ranbena** [comment]
Damnit, another codeclimate eslint plugin problem..
Might have to do with eslint channel compatibility 😒
@arikfr any reason not to switch to CircleCI step instead (assuming it's problem free)?

**Comment by ranbena** [comment]
Also, @arikfr I put the redirect script in `index.html` and `multi_org.html` (dunno what that is).
Should I put it in `signed_out.html` (a main template) as well?

**Comment by ranbena** [comment]
@arikfr I don't get the [pep8 error here](https://codeclimate.com/github/getredash/redash/pull/3609) - there are actually 2 lines..

File: package.json [hunk 3]
```diff
@@ -162,5 +163,20 @@
         "npm run test -- --bail --findRelatedTests"
       ]
     }
-  }
+  },
+  "//": "browserslist set to 'Async functions' compatibility",
+  "browserslist": [
```
Comment (arikfr) [inline package.json]: How about using configuration like we had before (`> 0.5%, last 2 versions, Firefox ESR, ie 11, not dead`) so we don't have to update this list everytime browser versions update? I mean not necessarily the same one, but along the lines of `> 0.5%, last 2 versions` etc instead of hardcoded versions.

File: redash/templates/unsupported.html [hunk 4]
```diff
@@ -0,0 +1,61 @@
+<!DOCTYPE html>
```
Comment (arikfr) [inline redash/templates/unsupported.html]: This file should be in `client/app` and we need to make sure webpack copies it into dist.

File: package.json (hunk 3 above)
Comment (ranbena) [reply package.json]: > so we don't have to update this list every time browser versions update

Why would you need to? We should revisit this list when:
1. There are lower browser versions we would like to support. Won't happen cause we've looked at the browser stats.
2. As a performance optimization to lower `app.js` file size. That can be done periodically.

> instead of hardcoded version

The advantage of hardcoded versions is that they allow to easily and reliably determine if a user's browser is supported or not. But if we define sth like "last 2 versions" you would have no clear cutoff point (cause under last 2 versions doesn't mean you can't use Redash).

File: redash/templates/unsupported.html (hunk 4 above)
Comment (ranbena) [reply redash/templates/unsupported.html]: Done.

Just realized `index.html` and `multi_org.html` are exactly the same. Intentional?

Comment (arikfr) [reply redash/templates/unsupported.html]: You still need a Flask route serving it.

Comment (ranbena) [reply redash/templates/unsupported.html]: The page is configured as a static asset `https://domain.com/static/unsupported.html` - so doesn't need it, nay?

Comment (arikfr) [reply redash/templates/unsupported.html]: You're right. I didn't notice you updated the URL 👍

**Comment by arikfr** [comment]
👍
