### PR TITLE
Work around a resizing issue.

### LINKED ISSUE #3353: Query Editor view port occasionally panics in Firefox/Chrome
### Issue Summary

Under certain circumstances, the view area in my query editor shrinks to just a few lines. See the attached gif.

bugged-editor

### Steps to Reproduce

I'm not able to reliably reproduce this bug. But I've stopped using Firefox because it happens frequently enough. I can resolve the issue by resizing the browser window.

### Technical details:

* Redash Version: 431d6fa
* Browser/OS: Firefox Quantum
* How did you install Redash: Skas

### PR DESCRIPTION
**Pull request by jezdez**
Fix #3353.

screen-recording-2019-02-07-14-23-00

### CODE REVIEW

File: client/app/components/QueryEditor.jsx [hunk 1]
```diff
@@ -217,6 +217,12 @@ class QueryEditor extends React.Component {
     localOptions.set('liveAutocomplete', state);
   };
 
+  componentDidUpdate = () => {
+    // Work-around for a resizing issue, see https://github.com/getredash/redash/issues/3353
```
Comment (arikfr) [inline client/app/components/QueryEditor.jsx]:
```suggestion
    // ANGULAR_REMOVE_ME  Work-around for a resizing issue, see https://github.com/getredash/redash/issues/3353
```

(so we remember to get rid of this)
