### PR TITLE
Fix: Refresh schedule phrase overlaps title

### LINKED ISSUE #3248: Bug: Refresh schedule phrase overlaps title
### Issue Summary
Refresh schedule phrase overlaps title when long enough.

screen shot 2019-01-03 at 18 09 19

(this bug originates from #2426 which has yet to land)

### PR DESCRIPTION
**Pull request by ranbena**
Closes #3248

#### The fix

Made phrase shorter - longest string fits both versions:
screen shot 2019-01-03 at 20 48 29

screen shot 2019-01-03 at 20 48 38

#### Bonus

Added tooltip to show full details on hover
screen shot 2019-01-04 at 8 05 38

Added css style to ensure string doesn't break like so:
screen shot 2019-01-03 at 20 58 00

### CODE REVIEW

File: client/app/filters/index.js [hunk 1]
```diff
@@ -57,22 +56,7 @@ export function scheduleHumanize(schedule) {
...
-      .local()
-      .format('HH:mm');
-    scheduleString += `at ${localTime} `;
-  }
-
-  if (schedule.day_of_week) {
-    scheduleString += `on ${schedule.day_of_week}`;
-  }
-  return scheduleString;
+  return `Every ${count} ${interval} `;
```
Comment (arikfr) [inline client/app/filters/index.js]: What will it print for "Every Tuesday at 16:00"?

Comment (ranbena) [reply client/app/filters/index.js]: "Every 1 week(s)"

Comment (ranbena) [reply client/app/filters/index.js]: Sure I can make it into a new component 👍🏻

Comment (arikfr) [reply client/app/filters/index.js]: The benefit of implementing the component is that users with read only access to the query will be able to see the real schedule (otherwise it's available only in the dialog).

Comment (ranbena) [reply client/app/filters/index.js]: Done!

**Comment by ranbena** [comment]
Percy found [a bug](https://percy.io/Redash/redash/builds/1296181?utm_campaign=Redash&utm_content=redash&utm_source=github_status) in my implementation! @arikfr 😃

**Comment by arikfr** [comment]
> Percy found a bug in my implementation! @arikfr 😃

Nice!!
