### PR TITLE
Fix: Refresh schedule interval count doesn't adhere to permission rules

### LINKED ISSUE #3263: Bug: Refresh schedule interval count doesn't adhere to permission rules
#### Issue Summary

Interval count dropdown menu items are hardcoded to be 1-59 minutes, 1-23 hours etc, although should be derived from `<ScheduleDialog>`'s `refreshOptions` prop.

#### Steps to Reproduce

1. Open existing query.
2. Click Refresh Schedule phrase which opens dialog.
3. Choose option "Minute(s)" in dropdown.
4. Click preceding number dropdown.

Expected: Shows menu items - 1, 5, 10, 15, 30.
Actual: Shows menu items 1 to 59.

### PR DESCRIPTION
**Pull request by ranbena**
Fixes #3263.

#### The bug
Not a programatic bug but rather a wrong feature implementation.
Interval counts were set as hardcoded ranges instead of deriving from `props.refreshOptions`.

#### The fix
Now `intervals` returns grouped count by interval type.
```js
{
  [IntervalEnum: NEVER]: [],
  [IntervalEnum: MINUTES]: [1, 5, 10, 15, 30],
  [IntervalEnum: HOURS]: [1, .. , 12],
  [IntervalEnum: DAYS]: [1],
  [IntervalEnum: WEEKS]: [1, 2, 4.28],
}
```
:raised_back_of_hand: 'Days' has only one value, 'Weeks' has a fraction (30 days)

#### Bonus fix
The code assumed all interval types included a "1" count value.

### CODE REVIEW

**Comment by ranbena** [comment]
@arikfr there are a few approaches regarding the week 4.28:
#### Floor number to 4.
* Pros: Ez implementation.
* Cons: a) 30 days is not 4 weeks - confusion risk. b) Allowing "day of week" choice on 4 weeks doesn't make much sense.

#### Convert "4.28 weeks" to "30 days".
* Pros: Mild implementation effort.
* Cons: UX confusion - doesn't abide by implicit ascending order.
Could be resolved if all interval options are visible at once.

The downside is the long-ass list but UX trumps UI imho.

**Comment by arikfr** [comment]
I think the long ass list wins. 👍

File: client/app/components/queries/ScheduleDialog.jsx [hunk 1]
```diff
@@ -44,31 +36,31 @@ class ScheduleDialog extends React.Component {
...
+    const { time, interval: seconds, day_of_week: day } = newSchedule;
+    const { interval } = secondsToInterval(seconds);
     const [hour, minute] = time ? localizeTime(time).split(':') : [null, null];
 
     return {
       hour,
       minute,
-      count: interval.count ? String(interval.count) : '1',
-      interval: interval.interval || IntervalEnum.NEVER,
+      seconds,
```
Comment (ranbena) [inline client/app/components/queries/ScheduleDialog.jsx]: Swapped `count` for the original `seconds` since it serves as a better select option value.

File: client/app/components/queries/ScheduleDialog.jsx [hunk 2]
```diff
@@ -44,31 +36,31 @@ class ScheduleDialog extends React.Component {
...
+      interval,
```
Comment (ranbena) [inline client/app/components/queries/ScheduleDialog.jsx]: Updated `secondsToInterval` to return `IntervalEnum.NEVER` when no interval exists.

**Comment by ranbena** [comment]
Lines: +34 −56 😜

File: client/app/filters/index.js [hunk 3]
```diff
@@ -30,7 +33,7 @@ export function secondsToInterval(seconds) {
     count /= 24;
     interval = IntervalEnum.DAYS;
   }
-  if (count >= 7 && interval === IntervalEnum.DAYS) {
+  if (count >= 7 && !(count % 7) && interval === IntervalEnum.DAYS) {
```
Comment (ranbena) [inline client/app/filters/index.js]: Stays "days" if `count` is a fraction.

**Comment by arikfr** [comment]
👍
