### PR TITLE
Fix: Download Dataset does not work when not logged in

### LINKED ISSUE #1247: Download Dataset does not work when not logged in
### Issue Summary

Using a query public URL, trying to download the dataset as a CSV when not logged in fails
### Steps to Reproduce
1. Create a query that returns a table
2. Create a public link using "embed" (use the src argument)
3. Open the link from an **anonymous** browser window
4. Click Download Dataset CSV

Getting 
image
### Technical details:
- Redash Version:  0.11.1+b2095
- Browser/OS: Chrome / Mac

### PR DESCRIPTION
**Pull request by phpcodecrafting**
This fixes #1247 where the download links on a visualization's public embed URL do not work if logged out of redash.

### CODE REVIEW

File: rd_ui/app/scripts/embed.js [hunk 1]
```diff
@@ -49,6 +49,7 @@ angular.module('redash', [
        $scope.embed = true;
        $scope.visualization = visualization;
        $scope.query = visualization.query;
+       $scope.api_key = $location.search()['api_key'];
```
Comment (arikfr) [inline rd_ui/app/scripts/embed.js]: Should be `apiKey`. Other than - perfect. 👍 Thanks!

Comment (phpcodecrafting) [inline rd_ui/app/scripts/embed.js]: Good point. Corrected and pushed.

**Comment by arikfr** [comment]
Thanks!
